### 경매 입찰 생성(성공)
POST localhost:19097/api/v1/auctions/7422cf34-f259-4bdc-ba26-4b81cef4007e
Content-Type: application/json
X-User-Role: ROLE_USER
X-User-Id: 3
#Authorization: Bearer {{$auth.token("")}}

{
  "bid": "60000"
}

### 경매 입찰 생성(실패)
POST localhost:19097/api/v1/auctions/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
X-User-Role: ROLE_USER
X-User-Id: 1
#Authorization: Bearer {{$auth.token("")}}

{
  "bid": "30000"
}