### 경매 이벤트 생성(성공)
POST localhost:19097/api/v1/auctions
Content-Type: application/json
X-User-Role: ROLE_ADMIN
#X-User-Id: 1
#Authorization: Bearer {{$auth.token("")}}

{
  "auctionProductId": "c2b35dd1-d53a-420b-86cb-171e15766098",
  "startingBid": "30000",
  "startTime": "2025-04-17T16:08:00",
  "endTime": "2025-04-21T12:20:00"
}

### 경매 이벤트 생성 (실패)
