### 경매 이벤트 생성(성공)
POST localhost:19097/api/v1/auctions
Content-Type: application/json
#X-User-Id: 1
#Authorization: Bearer {{$auth.token("")}}

{
  "productId": "8a463aa4-b1dc-4f27-9c3f-53b94dc45e74",
  "title": "50000",
  "description": "2025-04-21T12:00:00",
  "endTime": "2025-04-21T01:00:00"
}

### 경매 이벤트 생성 (실패)
