### 경매 낙찰자 주문 생성(성공)
POST localhost:19097/api/v1/auctions/788fabfe-71c2-4c95-a783-f492806707df/purchase
Content-Type: application/json
X-User-Role: ROLE_USER
X-User-Id: 3
#Authorization: Bearer {{$auth.token("")}}

{
  "orderType": "AUCTION",
  "productId": "54fc5e98-969a-44af-93d4-ab720899b2cf",
  "quantity": "1",
  "price": "60000"
}


