### 경매 낙찰자 주문 생성(성공)
POST localhost:19097/api/v1/auctions/bd3dc030-2435-4326-a679-fc97e3f3e42f/purchase
Content-Type: application/json
X-User-Id: 2
#Authorization: Bearer {{$auth.token("")}}

{
  "orderType": "AUCTION",
  "productId": "237b8c90-0d8e-4b42-b7db-f56410e55b34",
  "quantity": "1",
  "price": "48000"
}


