### 경매 이벤트 생성(성공)
POST localhost:19097/api/v1/auctions
Content-Type: application/json
X-User-Role: ROLE_ADMIN
#X-User-Id: 1
#Authorization: Bearer {{$auth.token("")}}

{
  "auctionProductId": "237b8c90-0d8e-4b42-b7db-f56410e55b34",
  "startingBid": "50000",
  "startTime": "2025-04-21T12:00:00",
  "endTime": "2025-04-21T12:20:00"
}

### 경매 이벤트 생성 (실패)
