server:
  port: 19097

spring:
  application:
    name: auction-service

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/eureka-client.yml
      - classpath:properties/actuator.yml
      - classpath:properties/redis.yml
  profiles:
    active: local
