### 경매 상품 생성(성공)
POST localhost:19097/api/v1/auction-products
Accept: application/json
Content-Type: application/json
X-User-Role: ROLE_ADMIN
#X-User-Id: 1
#Authorization: Bearer {{$auth.token("")}}

{
  "productId": "c2b35dd1-d53a-420b-86cb-171e15766098"
}

### 경매 상품 생성 (실패)
