### 경매 상품 생성(성공)
POST localhost:19097/api/v1/auction-products
Accept: application/json
Content-Type: application/json
X-User-Role: ROLE_ADMIN
#X-User-Id: 1
#Authorization: Bearer {{$auth.token("")}}

{
  "productId": "237b8c90-0d8e-4b42-b7db-f56410e55b34"
}

### 경매 상품 생성 (실패)
